# Generated by Django 3.1.3 on 2020-11-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('TCO', models.FloatField(blank=True)),
                ('TVO', models.FloatField(blank=True)),
                ('NET', models.FloatField(blank=True)),
                ('PP', models.FloatField(blank=True)),
                ('ROI', models.FloatField(blank=True)),
                ('CapEx', models.FloatField(blank=True)),
                ('OneTime', models.FloatField(blank=True)),
                ('OnGoing', models.FloatField(blank=True)),
                ('Revenue', models.FloatField(blank=True)),
                ('Saving', models.FloatField(blank=True)),
                ('Avoid', models.FloatField(blank=True)),
                ('CostGrade', models.FloatField(blank=True)),
                ('ValueScore', models.FloatField(blank=True)),
                ('RiskScore', models.FloatField(blank=True)),
                ('BlendedScore', models.FloatField(blank=True)),
                ('CalcPriority', models.FloatField()),
                ('OverridePriority', models.FloatField()),
                ('dsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dataset')),
            ],
        ),
    ]
