# Generated by Django 3.1.3 on 2020-12-10 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kfile', models.CharField(max_length=200)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('features', models.IntegerField()),
                ('TCO', models.IntegerField()),
                ('TVO', models.IntegerField()),
                ('NET', models.IntegerField()),
                ('PP', models.IntegerField()),
                ('ROI', models.IntegerField()),
                ('CapEx', models.IntegerField()),
                ('OneTime', models.IntegerField()),
                ('OnGoing', models.IntegerField()),
                ('Revenue', models.IntegerField()),
                ('Saving', models.IntegerField()),
                ('Avoid', models.IntegerField()),
                ('CostGrade', models.IntegerField()),
                ('ValueScore', models.IntegerField()),
                ('RiskScore', models.IntegerField()),
                ('BlendedScore', models.IntegerField()),
                ('CalcPriority', models.IntegerField()),
                ('OverridedPriority', models.IntegerField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='OverridePriority',
        ),
        migrations.AddField(
            model_name='data',
            name='OverridedPriority',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='accepted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='approved',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='budget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Avoid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BlendedScore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CalcPriority',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CapEx',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CostGrade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='NET',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='OnGoing',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='OneTime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='ROI',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Revenue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RiskScore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Saving',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='TCO',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='TVO',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='ValueScore',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField()),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.data')),
                ('dsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dataset')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model')),
            ],
        ),
    ]
