# Generated by Django 3.1.3 on 2020-11-07 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='OverridePriority',
        ),
        migrations.AddField(
            model_name='data',
            name='OverridedPriority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Avoid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BlendedScore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CalcPriority',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CapEx',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CostGrade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='NET',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='OnGoing',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='OneTime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='ROI',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Revenue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RiskScore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Saving',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='TCO',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='TVO',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='ValueScore',
            field=models.FloatField(null=True),
        ),
    ]
